services:
  - type: web
    name: emoji-war
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CHANNEL_ID
        value: UCT24pImU78QB7I8a6gofYyA
